# Generated by Django 6.1 on 2026-08-28 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('design', 'Design'), ('music', 'Music'), ('arts', 'Arts'), ('language', 'Language'), ('business', 'Business'), ('fitness', 'Fitness'), ('other', 'Other')], max_length=50)),
                ('skill_type', models.CharField(choices=[('offer', 'I can teach this'), ('want', 'I want to learn this')], max_length=10)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('icon', models.CharField(default='bi bi-tools', max_length=50)),
                ('color', models.CharField(default='linear-gradient(135deg, #7c3aed, #8b5cf6)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
